### ISSUE TITLE
Cash flow diagrams documentation

### ISSUE THREAD

**Issue by joastbg** [HIPERFIT/HQL#19]
Change colors, or make monochrome, hard so see when printed on black/white laser printer.

**Comment by andreasbock** [comment]
Why sacrifice quality of the digital version to cater for the analog..?
Black and white, even.

**Comment by joastbg** [comment]
Doesnt have to sacrifice anything, just consider people printing using black/white printers for example increase monochrome contrast, red/green etc looks the same when printed.
